### ISSUE TITLE
Move this repository to the "orocos" group and delete hydro-devel branch

### ISSUE THREAD

**Issue by jbohren** [orocos/rtt_ros_comm#3]
As per earlier discussions in https://github.com/orocos-toolchain/rtt_ros_integration/pull/7#issuecomment-30353164, it makes sense to move this repository to the  [orocos](https://github.com/orocos) organization since it's dependent on the core toolchain.

Also, since this tree has been merged into the new rtt_ros_integration (https://github.com/orocos-toolchain/rtt_ros_integration/pull/6) we should probably delete the hydro-devel branch.

**Comment by smits** [comment]
Done!
